CREATE TABLE `dictionary` (
	`name` varchar(50) DEFAULT NULL,
	`image` varchar(200) DEFAULT NULL,
	`ATTR_1` varchar(57) DEFAULT NULL,
	`ATTR_2` varchar(17) DEFAULT NULL,
	`ATTR_3` varchar(48) DEFAULT NULL,
	`ATTR_4` varchar(6) DEFAULT NULL,
	`ATTR_5` varchar(12) DEFAULT NULL,
	`ATTR_6` varchar(2) DEFAULT NULL,
	`ATTR_7` varchar(7) DEFAULT NULL,
	`ATTR_8` varchar(8) DEFAULT NULL,
	`ATTR_9` varchar(72) DEFAULT NULL,
	`ATTR_10` varchar(118) DEFAULT NULL,
	`ATTR_11` varchar(108) DEFAULT NULL,
	`ATTR_12` varchar(59) DEFAULT NULL,
	`ATTR_13` varchar(10) DEFAULT NULL,
	`ATTR_14` varchar(20) DEFAULT NULL,
	`ATTR_15` varchar(59) DEFAULT NULL,
	`ATTR_16` varchar(6) DEFAULT NULL,
	`ATTR_17` varchar(83) DEFAULT NULL,
	`ATTR_18` varchar(36) DEFAULT NULL,
	`ATTR_19` varchar(16) DEFAULT NULL,
	`ATTR_20` varchar(13) DEFAULT NULL,
	`ATTR_21` varchar(3) DEFAULT NULL,
	`ATTR_22` varchar(3) DEFAULT NULL,
	`ATTR_23` varchar(14) DEFAULT NULL,
	`ATTR_24` varchar(8) DEFAULT NULL,
	`ATTR_25` varchar(79) DEFAULT NULL,
	`ATTR_26` varchar(32) DEFAULT NULL,
	`ATTR_27` varchar(38) DEFAULT NULL,
	`ATTR_28` varchar(13) DEFAULT NULL,
	`ATTR_29` varchar(31) DEFAULT NULL,
	`ATTR_30` varchar(10) DEFAULT NULL,
	`ATTR_31` varchar(14) DEFAULT NULL,
	`ATTR_32` varchar(5) DEFAULT NULL,
	`ATTR_33` varchar(101) DEFAULT NULL,
	`ATTR_34` varchar(327) DEFAULT NULL,
	`ATTR_35` varchar(48) DEFAULT NULL,
	`ATTR_36` varchar(106) DEFAULT NULL,
	`ATTR_37` varchar(24) DEFAULT NULL,
	`ATTR_38` varchar(53) DEFAULT NULL,
	`ATTR_39` varchar(28) DEFAULT NULL,
	`ATTR_40` varchar(8) DEFAULT NULL,
	`ATTR_41` varchar(54) DEFAULT NULL,
	`ATTR_42` varchar(5) DEFAULT NULL,
	`ATTR_43` varchar(95) DEFAULT NULL,
	`ATTR_44` varchar(34) DEFAULT NULL,
	);


flower_info = {
	'학명': 'ATTR_1',
	'과명': 'ATTR_2',
	'유통명': 'ATTR_3',
	'관리수준': 'ATTR_4',
	'관리요구': 'ATTR_5',
	'생장속도': 'ATTR_6',
	'생육온도': 'ATTR_7',
	'최저온도': 'ATTR_8',
	'광요구도': 'ATTR_9',
	'배치 장소': 'ATTR_10',
	'물주기': 'ATTR_11',
	'비료정보': 'ATTR_12',
	'번식 방법': 'ATTR_13',
	'번식 시기': 'ATTR_14',
	'병충해관리정보': 'ATTR_15',
	'습도': 'ATTR_16',
	'토양': 'ATTR_17',
	'원산지': 'ATTR_18',
	'분류': 'ATTR_19',
	'생육형태': 'ATTR_20',
	'생장높이(cm)': 'ATTR_21',
	'생장너비(cm)': 'ATTR_22',
	'실내정원구성': 'ATTR_23',
	'생태형': 'ATTR_24',
	'잎형태': 'ATTR_25',
	'잎무늬': 'ATTR_26',
	'잎색': 'ATTR_27',
	'꽃피는 계절': 'ATTR_28',
	'꽃색': 'ATTR_29',
	'열매 맺는 계절': 'ATTR_30',
	'열매색': 'ATTR_31',
	'향기': 'ATTR_32',
	'TIP': 'ATTR_33',
	'특별관리정보': 'ATTR_34',
	'독성': 'ATTR_35',
	'병충해 관리': 'ATTR_36',
	'생장형': 'ATTR_37',
	'번식': 'ATTR_38',
	'식물 분류': 'ATTR_39',
	'형태 분류': 'ATTR_40',
	'엽색 변화': 'ATTR_41',
	'뿌리형태': 'ATTR_42',
	'꽃': 'ATTR_43',
	'고온다습': 'ATTR_44',
}

image_len:210